### PR TITLE
Seat flow

### PR DESCRIPTION
**Pull request by tomgp**
adding FT logo and updated/ source stamp to the SVG itself for portability.

removing explicit seat listing now that the figures are on the links.

moving the description up to occupy the space where that list was

### CODE REVIEW

**Comment by callumlocke** [comment]
I can't see the logo?

**Comment by tomgp** [comment]
really? should be bottom left...
screen shot 2015-02-20 at 13 45 12 2

**Comment by tomgp** [comment]
can you see the date stamp as part of the SVG?

**Comment by tomgp** [comment]
sorry, that's right isn't it

**Comment by callumlocke** [comment]
ha yes it's right. my first pull didn't get everything for some reason.

For me the coloured blocks for "PC" and "UKIP" are missing on the right hand side only:
image

is that a rounding-down-to-zero problem? can you force it to minimum 1px?

**Comment by tomgp** [comment]
hmm, I think the code is using Math.max(value, 1) to determine the thickness. Will check

**Comment by tomgp** [comment]
OK, I did that for the lines but not for then nodes at their ends.
if you pull again that should be fixed

**Comment by callumlocke** [comment]
cool. can you squash these into one commit?

**Comment by tomgp** [comment]
yep please do

**Comment by tomgp** [comment]
sorry, missunderstood, I'll do that now

**Comment by tomgp** [comment]
OK, having some weird problems now, saying I have merge conflicts when I rebase to squash...

**Comment by tomgp** [comment]
OK, have I managed to squash those commits? what should I see in gihub?

**Pull request merged**
